version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: poor_to_rich_mariadb
    ports:
      - "${DB_BINDING_PORT}:${DB_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: poor_to_rich_mysqld_exporter
    volumes:
      - ./mysqld-exporter.cnf:/.my.cnf
    ports:
      - "9104:9104"
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: poor_to_rich_redis
    ports:
      - "${REDIS_BINDING_PORT:-6379}:${REDIS_PORT}"
    volumes:
      - redis_data:/var/lib/redis

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: poor_to_rich_redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    container_name: poor_to_rich_prometheus
    ports:
      - ${PROMETHEUS_BINDING_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - redis-exporter
      - mysqld-exporter

  grafana:
    image: grafana/grafana
    ports:
      - ${GRAFANA_BINDING_PORT}:${GRAFANA_PORT}

  app:
    build: .
    container_name: poor_to_rich_application
    depends_on:
      - db
      - redis
    ports:
      - "${APP_BINDING_PORT}:${APP_PORT}"
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: -Duser.timezone=Asia/Seoul
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      KAKAO_KEY: ${KAKAO_KEY}
      KAKAO_SECRET: ${KAKAO_SECRET}
      KAKAO_ADMIN: ${KAKAO_ADMIN}
    env_file:
      - .env
volumes:
  mariadb_data:
  redis_data:
