spring:
  datasource:
    hikari:
      maximum-pool-size: 8
      minimum-idle: 3
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

server:
  tomcat:
    threads:
      max: 25
      min-spare: 5
    accept-count: 20
    max-connections: 80

ranking:
  scheduler:
    batch-size: 100
  task-executor:
    core-pool-size: 3
    max-pool-size: 3
    queue-capacity: 100

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    com.zaxxer.hikari: DEBUG
